# Setup my path
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/sbin
PATH=$HOME/bin:$PATH
PATH=/usr/local/mysql/bin:$PATH
PATH=$PATH:$HOME/.tmuxifier/bin
PATH=$PATH:/opt/homebrew/bin
export PATH=$PATH

# Setup git auto-completion
export GIT_COMPLETION_CHECKOUT_NO_GUESS=1
zstyle ':completion:*:*:git:*' script ~/.zsh/_git/git-completion.bash
fpath=(~/.zsh/_git $fpath)
autoload -Uz compinit && compinit

# Setup nvm
export NVM_DIR="$HOME/.nvm"
NVM_INSTALL_DIR="/opt/homebrew/Cellar/nvm/0.39.0"
[ -s "$NVM_INSTALL_DIR/nvm.sh" ] && \. "$NVM_INSTALL_DIR/nvm.sh"

# Add my PROMPT
source ~/.zsh/prompt.zsh

# Aliases
alias ls='ls -AFs1kG'
alias tmux='tmux -2'
source ~/.zsh/aliases.zsh

# Make the time format more standard
export TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'

# Remove some things from wordchars to make option-delete work better
WORDCHARS="*?_-.[]~=&;!#$%^(){}<>"

# Allow #s on lines
setopt interactivecomments

# Setup antigen & plugins
source ~/.zsh/antigen.zsh
antigen bundle zsh-users/zsh-syntax-highlighting

# history options
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=~/.history
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
